## s15_csv_to_latex.jl — Generate LaTeX tables from comparison CSV
#
# Usage:
#   julia --project=. scripts/s15_csv_to_latex.jl --csv results/example_1/comparison.csv
#   julia --project=. scripts/s15_csv_to_latex.jl --csv results/example_1/comparison.csv --dim 100,200,300
#   julia --project=. scripts/s15_csv_to_latex.jl --csv results/example_2/comparison.csv --format sfp
#
# For the 3 weak-comparison tables, use `scripts/w51_weak_latex.jl` instead
# (it batches all three CSVs and emits them into `../paper/tables/`).
#
# Options:
#   --csv <path>        Path to comparison CSV (required)
#   --dim <d1,d2,...>   Filter dimensions (default: all)
#   --format <type>     Table format: "vip" (default), "sfp", or "weak"
#   --output <path>     Save to file instead of stdout
#
# Formats:
#   "vip"  — one table per dim, rows=tolerance, columns=algorithms×[time,iter]
#   "sfp"  — one table, rows=instance, columns=algorithms×[time,iter]
#   "weak" — COMBINED tolerance table: rows=(dim,tol) blocks, columns=algos×[iter,time]

include("../src/includes.jl")
using Statistics: mean, median
# Aggregator policy (locked 2026-04-26): TIME → median (robust to single-instance
# GC pauses), ITER → mean (deterministic, paper convention). Caption auto-reflects.

opts, _ = parse_args(ARGS)
csv_path = get(opts, "csv", "")
if isempty(csv_path)
    error("Usage: --csv <path_to_csv> [--dim 100,200,300] [--format vip|sfp|weak] [--output file.tex]")
end

format = get(opts, "format", "vip")
output_path = get(opts, "output", "")

df = CSV.read(csv_path, DataFrame)

# Filter dims if specified
dims_str = get(opts, "dim", "")
if !isempty(dims_str)
    dims = parse.(Int, split(dims_str, ","))
    df = filter(row -> row.Dimension in dims, df)
end

algorithms = unique(df.Algorithm)
# Force DIPCM to the rightmost (emphasis) position for paper-side consistency.
if "DIPCM" in algorithms
    algorithms = [a for a in algorithms if a != "DIPCM"]
    push!(algorithms, "DIPCM")
end
dims = sort(unique(df.Dimension))
errors = sort(unique(df.Error), rev=true)

# Redirect output if --output specified
if !isempty(output_path)
    mkpath(dirname(output_path))
end
io = isempty(output_path) ? stdout : open(output_path, "w")

println(io, "% Auto-generated by s15_csv_to_latex.jl")
println(io, "% Source: $csv_path")
println(io, "% Algorithms: $(join(algorithms, ", "))")
println(io, "% Dimensions: $(join(dims, ", "))")
println(io, "")

function format_time(t)
    if t < 0.001
        @sprintf("%.2e", t)
    elseif t < 1.0
        @sprintf("%.4f", t)
    elseif t < 100.0
        @sprintf("%.2f", t)
    else
        @sprintf("%.1f", t)
    end
end

if format == "vip"
    # ── VIP format: one table per dimension, averaged over instances ──
    for dim in dims
        df_dim = filter(row -> row.Dimension == dim, df)
        local n_algos = length(algorithms)
        local n_inst = length(unique(df_dim[!, "Problem Instance"]))

        println(io, "% ============ N = $dim ============")
        println(io, "\\begin{table}[htbp]")
        println(io, "\\centering")
        println(io, "{\\color{blue}")
        println(io, "\\caption{Median CPU time (seconds) and average iterations over $n_inst instances, \$N=$dim\$.}")
        println(io, "\\label{tab:comparison_n$(dim)}")
        println(io, "\\begin{tabular}{c*{$(n_algos)}{rr}}")
        println(io, "\\hline")
        println(io, "\\multicolumn{$(1 + 2*n_algos)}{c}{\$N=$dim\$}\\\\")
        println(io, "\\hline")

        # Algorithm headers
        local header_parts = [" "]
        for (i, algo) in enumerate(algorithms)
            sep = i < n_algos ? "|" : ""
            push!(header_parts, "\\multicolumn{2}{c$(sep)}{\\textbf{$algo}}")
        end
        println(io, join(header_parts, " & "), "\\\\")
        println(io, "\\cline{2-$(1 + 2*n_algos)}")

        # Sub-headers
        local subheader_parts = ["Error"]
        for _ in algorithms
            push!(subheader_parts, "Time")
            push!(subheader_parts, "No.\\ It.")
        end
        println(io, join(subheader_parts, " & "), "\\\\")
        println(io, "\\hline")

        # Data rows
        for err in errors
            err_exp = Int(round(log10(err)))
            row_parts = ["\$10^{$err_exp}\$"]

            for algo in algorithms
                df_cell = filter(r -> r.Algorithm == algo && abs(r.Error - err) < 1e-15, df_dim)

                if isempty(df_cell)
                    push!(row_parts, "--")
                    push!(row_parts, "--")
                    continue
                end

                conv_col = df_cell.Converged
                converged_flags = [c == true || c == "true" for c in conv_col]
                n_conv = count(converged_flags)

                if n_conv == 0
                    push!(row_parts, "--")
                    push!(row_parts, "\$-\$")
                else
                    conv_rows = df_cell[converged_flags, :]
                    med_time = median(conv_rows.Time)
                    avg_iter = mean(conv_rows.Iter)

                    if n_conv < nrow(df_cell)
                        # Partial convergence
                        push!(row_parts, format_time(med_time) * "*")
                        push!(row_parts, string(round(Int, avg_iter)) * "*")
                    else
                        push!(row_parts, format_time(med_time))
                        push!(row_parts, string(round(Int, avg_iter)))
                    end
                end
            end
            println(io, join(row_parts, " & "), " \\\\")
        end

        println(io, "\\hline")
        println(io, "\\end{tabular}")
        println(io, "}")
        println(io, "\\end{table}")
        println(io, "")
    end

elseif format == "sfp"
    # ── SFP format: per-instance table, all algorithms side by side ──
    instances = unique(df[!, "Problem Instance"])
    n_algos = length(algorithms)

    println(io, "\\begin{table}[htbp]")
    println(io, "\\centering")
    println(io, "{\\color{blue}")

    # Build column spec
    local col_spec = "c"
    for i in 1:n_algos
        sep = i < n_algos ? "|" : ""
        col_spec *= " S[exponent-mode = threshold,exponent-thresholds = -2:2] c"
        if i < n_algos
            col_spec *= " |"
        end
    end
    # Simpler approach: just use rr columns
    println(io, "\\begin{tabular}{c*{$(n_algos)}{rr}}")
    println(io, "\\hline")

    # Algorithm headers
    header_parts = ["\\multirow{2}{*}{Instance}"]
    for (i, algo) in enumerate(algorithms)
        sep = i < n_algos ? "|" : ""
        push!(header_parts, "\\multicolumn{2}{c$(sep)}{\\textbf{$algo}}")
    end
    println(io, join(header_parts, " & "), " \\\\")

    # Sub-headers
    subheader_parts = [""]
    for _ in algorithms
        push!(subheader_parts, "Time")
        push!(subheader_parts, "Iter")
    end
    println(io, join(subheader_parts, " & "), " \\\\")
    println(io, "\\hline")

    # Data rows — collect per-instance times/iters for later aggregation
    times_per_algo = Dict(a => Float64[] for a in algorithms)
    iters_per_algo = Dict(a => Float64[] for a in algorithms)

    for inst in instances
        # Extract instance number
        inst_num = match(r"(\d+)", inst)
        inst_label = inst_num !== nothing ? inst_num.match : inst

        row_parts = [inst_label]
        for algo in algorithms
            df_cell = filter(r -> r.Algorithm == algo && r[:"Problem Instance"] == inst, df)
            if isempty(df_cell)
                push!(row_parts, "--")
                push!(row_parts, "--")
            else
                t = df_cell.Time[1]
                it = df_cell.Iter[1]
                push!(times_per_algo[algo], t)
                push!(iters_per_algo[algo], it)
                push!(row_parts, format_time(t))
                push!(row_parts, string(round(Int, it)))
            end
        end
        println(io, join(row_parts, " & "), " \\\\")
    end

    # Summary row — median time (robust to single-instance JIT/GC outliers),
    # average iterations (deterministic, paper convention).
    println(io, "\\hline")
    summary_parts = ["Median/Avg"]
    for algo in algorithms
        if isempty(times_per_algo[algo])
            push!(summary_parts, "--")
            push!(summary_parts, "--")
        else
            push!(summary_parts, format_time(median(times_per_algo[algo])))
            push!(summary_parts, string(round(Int, mean(iters_per_algo[algo]))))
        end
    end
    println(io, join(summary_parts, " & "), " \\\\")

    println(io, "\\hline")
    println(io, "\\end{tabular}")
    println(io, "}")
    println(io, "\\caption{Median CPU time (seconds) and average iterations on the SFP \$L^2[0,1]\$ problem; per-instance values shown above.}")
    println(io, "\\label{tab:example2_comparizon}")
    println(io, "\\end{table}")
end

if format == "weak"
    # ── Combined-tolerance table: rows=(dim, tol), columns=algos × [iter, time] ──
    n_algos = length(algorithms)
    n_tols = length(errors)

    default_caption = "Weak-convergence regime comparison: iteration count and CPU time (seconds) per (dimension, tolerance). Averaged over instances; `\$-\$' indicates 0/N convergence across instances; starred values denote partial convergence."
    caption = get(opts, "caption", default_caption)
    label = get(opts, "label", "tab:weak_comparison")

    println(io, "\\begin{table}[htbp]")
    println(io, "\\centering")
    println(io, "\\small")
    println(io, "{\\color{blue}")
    println(io, "\\caption{$caption}")
    println(io, "\\label{$label}")

    # Columns: Dim | Tol | algo1 iter | algo1 time | algo2 iter | algo2 time | ...
    # Use | in the tabular spec to match the multicolumn separators below.
    colspec = "c|c" * repeat("|rr", n_algos)
    println(io, "\\begin{tabular}{$colspec}")
    println(io, "\\hline")

    # Header row 1: algorithms spanning 2 columns each
    header1 = ["\\multirow{2}{*}{\$N\$}", "\\multirow{2}{*}{tol}"]
    for algo in algorithms
        push!(header1, "\\multicolumn{2}{c|}{\\textbf{$algo}}")
    end
    # Last column has no right-bar
    header1[end] = replace(header1[end], "{c|}" => "{c}")
    println(io, join(header1, " & "), " \\\\")

    # Header row 2: iter, time
    header2 = ["", ""]
    for _ in algorithms
        push!(header2, "iter")
        push!(header2, "time")
    end
    println(io, join(header2, " & "), " \\\\")
    println(io, "\\hline")

    # Data rows: for each dim × tol
    for (i, dim) in enumerate(dims)
        df_dim = filter(row -> row.Dimension == dim, df)
        for (j, err) in enumerate(errors)
            err_exp = Int(round(log10(err)))
            # First column: dim label only on first tol row, blank otherwise
            dim_label = j == 1 ? "\$N=$dim\$" : ""
            row_parts = [dim_label, "\$10^{$err_exp}\$"]

            for algo in algorithms
                df_cell = filter(r -> r.Algorithm == algo && abs(r.Error - err) < 1e-15, df_dim)
                if isempty(df_cell)
                    push!(row_parts, "--")
                    push!(row_parts, "--")
                    continue
                end
                conv_col = df_cell.Converged
                converged_flags = [c == true || c == "true" for c in conv_col]
                n_conv = count(converged_flags)
                if n_conv == 0
                    push!(row_parts, "\$-\$")
                    push!(row_parts, "--")
                else
                    conv_rows = df_cell[converged_flags, :]
                    avg_iter = mean(conv_rows.Iter)
                    avg_time = mean(conv_rows.Time)
                    marker = n_conv < nrow(df_cell) ? "*" : ""
                    push!(row_parts, string(round(Int, avg_iter)) * marker)
                    push!(row_parts, format_time(avg_time) * marker)
                end
            end
            println(io, join(row_parts, " & "), " \\\\")
        end
        # Midrule between dimensions for readability
        if i < length(dims)
            println(io, "\\cline{1-$(2 + 2 * n_algos)}")
        end
    end

    println(io, "\\hline")
    println(io, "\\end{tabular}")
    println(io, "}")
    println(io, "\\end{table}")
end

if !isempty(output_path)
    close(io)
    println("Saved to: $output_path")
end
