## s15_csv_to_latex.jl — Generate LaTeX tables from comparison CSV
#
# Usage:
#   # Example 1 (VIP): averaged over instances, one table per dimension
#   julia --project=. scripts/s15_csv_to_latex.jl --csv results/example_1/comparison.csv
#   julia --project=. scripts/s15_csv_to_latex.jl --csv results/example_1/comparison.csv --dim 100,200,300
#
#   # Example 2 (SFP): per-instance table, single tolerance
#   julia --project=. scripts/s15_csv_to_latex.jl --csv results/example_2/comparison.csv --format sfp
#
# Options:
#   --csv <path>        Path to comparison CSV
#   --dim <d1,d2,...>   Filter dimensions (default: all)
#   --format <type>     Table format: "vip" (default) or "sfp"
#   --output <path>     Save to file instead of stdout

include("../src/includes.jl")
using Statistics: mean

opts, _ = parse_args(ARGS)
csv_path = get(opts, "csv", "")
if isempty(csv_path)
    error("Usage: --csv <path_to_csv> [--dim 100,200,300] [--format vip|sfp] [--output file.tex]")
end

format = get(opts, "format", "vip")
output_path = get(opts, "output", "")

df = CSV.read(csv_path, DataFrame)

# Filter dims if specified
dims_str = get(opts, "dim", "")
if !isempty(dims_str)
    dims = parse.(Int, split(dims_str, ","))
    df = filter(row -> row.Dimension in dims, df)
end

algorithms = unique(df.Algorithm)
dims = sort(unique(df.Dimension))
errors = sort(unique(df.Error), rev=true)

# Redirect output if --output specified
io = isempty(output_path) ? stdout : open(output_path, "w")

println(io, "% Auto-generated by s15_csv_to_latex.jl")
println(io, "% Source: $csv_path")
println(io, "% Algorithms: $(join(algorithms, ", "))")
println(io, "% Dimensions: $(join(dims, ", "))")
println(io, "")

function format_time(t)
    if t < 0.001
        @sprintf("%.2e", t)
    elseif t < 1.0
        @sprintf("%.4f", t)
    elseif t < 100.0
        @sprintf("%.2f", t)
    else
        @sprintf("%.1f", t)
    end
end

if format == "vip"
    # ── VIP format: one table per dimension, averaged over instances ──
    for dim in dims
        df_dim = filter(row -> row.Dimension == dim, df)
        local n_algos = length(algorithms)

        println(io, "% ============ N = $dim ============")
        println(io, "\\begin{table}[htbp]")
        println(io, "\\centering")
        println(io, "{\\color{blue}")
        println(io, "\\caption{CPU time (in seconds) and number of iterations for the $(n_algos) algorithms with \$N=$dim\$.}")
        println(io, "\\label{tab:comparison_n$(dim)}")
        println(io, "\\begin{tabular}{c*{$(n_algos)}{rr}}")
        println(io, "\\hline")
        println(io, "\\multicolumn{$(1 + 2*n_algos)}{c}{\$N=$dim\$}\\\\")
        println(io, "\\hline")

        # Algorithm headers
        local header_parts = [" "]
        for (i, algo) in enumerate(algorithms)
            sep = i < n_algos ? "|" : ""
            push!(header_parts, "\\multicolumn{2}{c$(sep)}{\\textbf{$algo}}")
        end
        println(io, join(header_parts, " & "), "\\\\")
        println(io, "\\cline{2-$(1 + 2*n_algos)}")

        # Sub-headers
        local subheader_parts = ["Error"]
        for _ in algorithms
            push!(subheader_parts, "Time")
            push!(subheader_parts, "No.\\ It.")
        end
        println(io, join(subheader_parts, " & "), "\\\\")
        println(io, "\\hline")

        # Data rows
        for err in errors
            err_exp = Int(round(log10(err)))
            row_parts = ["\$10^{$err_exp}\$"]

            for algo in algorithms
                df_cell = filter(r -> r.Algorithm == algo && abs(r.Error - err) < 1e-15, df_dim)

                if isempty(df_cell)
                    push!(row_parts, "--")
                    push!(row_parts, "--")
                    continue
                end

                conv_col = df_cell.Converged
                converged_flags = [c == true || c == "true" for c in conv_col]
                n_conv = count(converged_flags)

                if n_conv == 0
                    push!(row_parts, "--")
                    push!(row_parts, "\$-\$")
                else
                    conv_rows = df_cell[converged_flags, :]
                    avg_time = mean(conv_rows.Time)
                    avg_iter = mean(conv_rows.Iter)

                    if n_conv < nrow(df_cell)
                        # Partial convergence
                        push!(row_parts, format_time(avg_time) * "*")
                        push!(row_parts, string(round(Int, avg_iter)) * "*")
                    else
                        push!(row_parts, format_time(avg_time))
                        push!(row_parts, string(round(Int, avg_iter)))
                    end
                end
            end
            println(io, join(row_parts, " & "), " \\\\")
        end

        println(io, "\\hline")
        println(io, "\\end{tabular}")
        println(io, "}")
        println(io, "\\end{table}")
        println(io, "")
    end

elseif format == "sfp"
    # ── SFP format: per-instance table, all algorithms side by side ──
    instances = unique(df[!, "Problem Instance"])
    n_algos = length(algorithms)

    println(io, "\\begin{table}[htbp]")
    println(io, "\\centering")
    println(io, "{\\color{blue}")

    # Build column spec
    local col_spec = "c"
    for i in 1:n_algos
        sep = i < n_algos ? "|" : ""
        col_spec *= " S[exponent-mode = threshold,exponent-thresholds = -2:2] c"
        if i < n_algos
            col_spec *= " |"
        end
    end
    # Simpler approach: just use rr columns
    println(io, "\\begin{tabular}{c*{$(n_algos)}{rr}}")
    println(io, "\\hline")

    # Algorithm headers
    header_parts = ["\\multirow{2}{*}{Instance}"]
    for (i, algo) in enumerate(algorithms)
        sep = i < n_algos ? "|" : ""
        push!(header_parts, "\\multicolumn{2}{c$(sep)}{\\textbf{$algo}}")
    end
    println(io, join(header_parts, " & "), " \\\\")

    # Sub-headers
    subheader_parts = [""]
    for _ in algorithms
        push!(subheader_parts, "Time")
        push!(subheader_parts, "Iter")
    end
    println(io, join(subheader_parts, " & "), " \\\\")
    println(io, "\\hline")

    # Data rows
    total_time = Dict(a => 0.0 for a in algorithms)
    total_iter = Dict(a => 0.0 for a in algorithms)
    n_instances = length(instances)

    for inst in instances
        # Extract instance number
        inst_num = match(r"(\d+)", inst)
        inst_label = inst_num !== nothing ? inst_num.match : inst

        row_parts = [inst_label]
        for algo in algorithms
            df_cell = filter(r -> r.Algorithm == algo && r[:"Problem Instance"] == inst, df)
            if isempty(df_cell)
                push!(row_parts, "--")
                push!(row_parts, "--")
            else
                t = df_cell.Time[1]
                it = df_cell.Iter[1]
                total_time[algo] += t
                total_iter[algo] += it
                push!(row_parts, format_time(t))
                push!(row_parts, string(round(Int, it)))
            end
        end
        println(io, join(row_parts, " & "), " \\\\")
    end

    # Average row
    println(io, "\\hline")
    avg_parts = ["Average"]
    for algo in algorithms
        push!(avg_parts, format_time(total_time[algo] / n_instances))
        push!(avg_parts, string(round(Int, total_iter[algo] / n_instances)))
    end
    println(io, join(avg_parts, " & "), " \\\\")

    println(io, "\\hline")
    println(io, "\\end{tabular}")
    println(io, "}")
    println(io, "\\caption{Comparison of algorithms on the SFP.}")
    println(io, "\\label{tab:example2_comparizon}")
    println(io, "\\end{table}")
end

if !isempty(output_path)
    close(io)
    println("Saved to: $output_path")
end
